# Generated by Django 3.1.7 on 2021-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_discount_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
