# Generated by Django 3.1.7 on 2021-04-30 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_withdraw_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePlaceHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge', models.IntegerField()),
            ],
        ),
    ]
