# Generated by Django 3.1.7 on 2021-05-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
