# Generated by Django 3.1.7 on 2021-10-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20211015_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
