# Generated by Django 3.1.7 on 2021-05-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='token',
            field=models.TextField(max_length=128),
        ),
    ]
